CREATE TABLE IF NOT EXISTS PUBLIC.users 
(
	id SERIAL NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	username VARCHAR(65) NOT NULL,
	email VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (id)
);