
CREATE TABLE IF NOT EXISTS PUBLIC.orders (
    id SERIAL PRIMARY KEY,
    store_id INT NOT NULL,
    track_id BIGINT NOT NULL,
    number INT NOT NULL,
    payment_method_id INT,
    delivery_type_id INT NOT NULL,
    collaborator_id INT,
    is_scheduled BOOLEAN NOT NULL,
    items_value DECIMAL(18, 2) NOT NULL,
    delivery_value DECIMAL(18, 2) NOT NULL,
    discount_value DECIMAL(18, 2),
    discount_type INT,
    total_value DECIMAL(18, 2) NOT NULL,
    delivery_estimate_begin_at TIMESTAMP,
    delivery_estimate_end_at TIMESTAMP,
    delivered_at TIMESTAMP,
    table_reference VARCHAR(255),
    obs TEXT,
    status INT NOT NULL,
    is_online_menu BOOLEAN NOT NULL,
    user_external_id varchar(255),
    customer_name VARCHAR(255),
    customer_phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NULL DEFAULT NULL,
    shipping_address_id int,
    CONSTRAINT fk_store FOREIGN KEY (store_id) REFERENCES PUBLIC.stores(id),
    CONSTRAINT fk_order_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES PUBLIC.order_shipping_addresses(id)
);  
